# Make ML models for prediction gte parameters

In [1]:
%pip install --upgrade openpyxl pandas scikit-learn

Requirement already satisfied: openpyxl in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: pandas in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: scikit-learn in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (1.7.2)
Requirement already satisfied: et-xmlfile in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /Users/daniilandryushin/Projects/gte/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

# Parameters

In [7]:
from config import parameters as gtep

In [8]:
for alias, parameter in gtep.items():
    print(f"{alias:<15}: {parameter}")

l              : thermal_conductivity
hc             : heat_capacity
Cp             : heat_capacity_pressure
Cv             : heat_capacity_volume
k              : adiabatic_index
gc             : gas_const
eo             : excess_oxidizing
T              : static_temperature
P              : static_pressure
D              : staticdensity
TT             : total_temperature
PP             : total_pressure
DD             : total_density
m              : mass
v              : volume
a              : sound_speed
a_critical     : critical_sound_speed
c              : absolute_velocity
u              : portable_velocity
w              : relative_velocity
mf             : mass_flow
pipi           : total_pressure_ratio
pi             : static_pressure_ratio
titi           : total_temperature_ratio
ti             : static_temperature_ratio
mach           : mach_number
Nu             : nusselt_number
efficiency     : efficiency
effeff         : total_efficiency
peff           : pressure_efficiency
effburn        : efficiency_burn
power          : power

# Generate data

In [9]:
import time
from itertools import product
import numpy as np
import pandas as pd
from tqdm import tqdm
import pickle

from thermodynamics import gas_const, heat_capacity_p
from substance import Substance

In [10]:
def generate(**kwargs):
    """Генерация"""
    static, names, values = {}, [], []
    for k, v in kwargs.items():
        if isinstance(v, (tuple, list, np.ndarray)):
            names.append(k)
            values.append(v)
        else:
            static[k] = v

    for combination in product(*values):
        result = dict(zip(names, combination))
        yield {**static, **result}


def now() -> str:
    return time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime())

In [ ]:
substance_parameters = [
    *generate(
        **{
            gtep.mf: np.arange(1, 200 + 1, 5),
            gtep.TT: np.arange(250, 1050 + 1, 20),
            gtep.PP: np.arange(1, 20 + 1, 0.5) * 10**5,
        }
    )
]

with open(f"data/substance_parameters_{len(substance_parameters)}.pkl", "wb") as file:
    pickle.dump(substance_parameters, file)

len(substance_parameters)

65600

In [ ]:
with open("data/substance_parameters_65600.pkl", "rb") as file:
    substance_parameters = pickle.load(file)

len(substance_parameters)

65600

In [14]:
functions = {
    gtep.gc: lambda temperature: gas_const("air"),
    gtep.Cp: lambda temperature: heat_capacity_p("air", temperature),
}

## Air

In [17]:
def generate_air(**kwargs):
    """Генерация воздуха"""

    for combination in generate(**kwargs):
        yield Substance(
            combination["name"],
            composition=combination["composition"],
            parameters=combination["parameters"],
            functions=combination["functions"],
        )

In [ ]:
airs = [
    *generate_air(
        name="air",
        composition=({"N2": 0.78, "O2": 0.21, "Ar": 0.009, "CO2": 0.0004}),
        parameters=substance_parameters,
        functions=functions,
    )
]

with open(f"data/airs_{len(substance_parameters)}.pkl", "wb") as file:
    pickle.dump(airs, file)

len(airs)

13200

## Compressor

In [19]:
from gte import Compressor

In [20]:
data = []
for combination in generate(
    pipi=np.arange(1.1, 12.1 + 1, 1),
    effeff=np.arange(0.84, 0.94 + 0.01, 0.01),
    # leak=np.arange(0, 1 + 0.2, 0.2),
):
    for air in tqdm(airs):
        compressor = Compressor("compressor")
        # setattr(compressor, "leak", combination["leak"])
        setattr(compressor, gtep.pipi, combination["pipi"])
        setattr(compressor, gtep.effeff, combination["effeff"])

        compressor.solve(air)

        if compressor.is_real:
            data.append(compressor.summary)

100%|██████████| 13200/13200 [00:04<00:00, 2885.02it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2842.32it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2834.29it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2817.41it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2814.47it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2810.36it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2816.22it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2812.57it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2811.65it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2799.48it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2811.10it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2567.49it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2564.59it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2558.87it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2581.12it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2584.55it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2581.48it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2615.56it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2617.08it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2629.70it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2620.64it/s]
100%|██████████| 13200/13200 [00:04<00:00, 2656.69it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2201.63it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2197.28it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2199.11it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2201.75it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2196.88it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2213.73it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2215.35it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2223.30it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2242.94it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2248.52it/s]
100%|██████████| 13200/13200 [00:05<00:00, 2238.44it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2164.02it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2172.13it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2172.27it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2169.54it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2177.28it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2168.72it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2174.11it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2172.04it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2176.95it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2175.80it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2168.92it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2158.19it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2155.34it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2156.82it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2155.64it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2154.46it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2148.52it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2154.48it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2152.51it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2157.85it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2158.27it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2171.71it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2149.83it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2148.31it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2148.57it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2149.56it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2142.35it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2150.54it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2146.16it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2145.91it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2135.41it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2139.23it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2150.17it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2139.97it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2132.17it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2135.14it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2127.45it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2133.74it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2126.25it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2136.04it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2135.86it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2135.49it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2147.07it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2147.09it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2136.11it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2135.16it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2138.63it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2151.35it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2141.45it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2144.02it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2145.65it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2138.74it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2138.13it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2137.68it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2143.60it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2087.45it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2137.72it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2139.87it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2130.81it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2126.36it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2131.90it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2144.38it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2108.72it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2083.89it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2078.47it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2091.01it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2104.74it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2102.69it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2109.01it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2104.15it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2112.87it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2074.89it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2119.42it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2114.35it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2127.97it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2109.27it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2119.92it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2125.12it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2141.79it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2139.03it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2138.74it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2136.04it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2126.80it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2123.08it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2125.56it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2122.62it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2125.86it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2120.49it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2139.76it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2132.96it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2140.18it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2116.46it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2153.93it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2149.45it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2132.44it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2114.55it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2149.64it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2136.74it/s]
100%|██████████| 13200/13200 [00:06<00:00, 2135.24it/s]

In [ ]:
with open(f"data/compressor_{len(substance_parameters)}.pkl", "wb") as file:
    pickle.dump(data, file)

In [22]:
df = pd.DataFrame(data)
df

,name,inlet_mass_flow,inlet_total_temperature,inlet_total_pressure,outlet_mass_flow,outlet_total_temperature,outlet_total_pressure,outlet_gas_const,outlet_heat_capacity_pressure,outlet_total_density,outlet_adiabatic_index,outlet_critical_sound_speed,leak,total_pressure_ratio,total_efficiency,power
0,compressor,1,250,100000.0,1,258.243268,110000.0,287.14,1001.731420,1.483440,1.401824,294.206665,0,1.1,0.84,8.257334e+03
1,compressor,1,250,200000.0,1,258.243268,220000.0,287.14,1001.731420,2.966880,1.401824,294.206665,0,1.1,0.84,8.257334e+03
2,compressor,1,250,300000.0,1,258.243268,330000.0,287.14,1001.731420,4.450320,1.401824,294.206665,0,1.1,0.84,8.257334e+03
3,compressor,1,250,400000.0,1,258.243268,440000.0,287.14,1001.731420,5.933760,1.401824,294.206665,0,1.1,0.84,8.257334e+03
4,compressor,1,250,500000.0,1,258.243268,550000.0,287.14,1001.731420,7.417200,1.401824,294.206665,0,1.1,0.84,8.257334e+03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1742395,compressor,191,1050,1600000.0,191,1954.275722,19360000.0,287.14,1246.846675,34.500534,1.299196,796.350164,0,12.1,0.94,2.084862e+08
1742396,compressor,191,1050,1700000.0,191,1954.275722,20570000.0,287.14,1246.846675,36.656818,1.299196,796.350164,0,12.1,0.94,2.084862e+08
1742397,compressor,191,1050,1800000.0,191,1954.275722,21780000.0,287.14,1246.846675,38.813101,1.299196,796.350164,0,12.1,0.94,2.084862e+08
1742398,compressor,191,1050,1900000.0,191,1954.275722,22990000.0,287.14,1246.846675,40.969384,1.299196,796.350164,0,12.1,0.94,2.084862e+08
1742399,compressor,191,1050,2000000.0,191,1954.275722,24200000.0,287.14,1246.846675,43.125668,1.299196,796.350164,0,12.1,0.94,2.084862e+08

# ML

In [19]:
import os
import pickle
from colorama import Fore

import pandas as pd

from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error

In [37]:
MODELS = (
    LinearRegression,
    DecisionTreeRegressor,
    # RandomForestRegressor,
)
METRICS = (mean_absolute_error, mean_squared_error)

In [21]:
os.listdir("data")

['substance_parameters_65600.pkl', 'compressor_13200.pkl', 'airs_65600.pkl']

In [22]:
with open("data/compressor_13200.pkl", "rb") as file:
    db = pickle.load(file)
len(db)

1742400

In [27]:
df = pd.DataFrame(db)
display(df)

,name,inlet_mass_flow,inlet_total_temperature,inlet_total_pressure,outlet_mass_flow,outlet_total_temperature,outlet_total_pressure,outlet_gas_const,outlet_heat_capacity_pressure,outlet_total_density,outlet_adiabatic_index,outlet_critical_sound_speed,leak,total_pressure_ratio,total_efficiency,power
0,compressor,1,250,100000.0,1,258.243268,110000.0,287.14,1001.731420,1.483440,1.401824,294.206665,0,1.1,0.84,8.257334e+03
1,compressor,1,250,200000.0,1,258.243268,220000.0,287.14,1001.731420,2.966880,1.401824,294.206665,0,1.1,0.84,8.257334e+03
2,compressor,1,250,300000.0,1,258.243268,330000.0,287.14,1001.731420,4.450320,1.401824,294.206665,0,1.1,0.84,8.257334e+03
3,compressor,1,250,400000.0,1,258.243268,440000.0,287.14,1001.731420,5.933760,1.401824,294.206665,0,1.1,0.84,8.257334e+03
4,compressor,1,250,500000.0,1,258.243268,550000.0,287.14,1001.731420,7.417200,1.401824,294.206665,0,1.1,0.84,8.257334e+03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1742395,compressor,191,1050,1600000.0,191,1954.275722,19360000.0,287.14,1246.846675,34.500534,1.299196,796.350164,0,12.1,0.94,2.084862e+08
1742396,compressor,191,1050,1700000.0,191,1954.275722,20570000.0,287.14,1246.846675,36.656818,1.299196,796.350164,0,12.1,0.94,2.084862e+08
1742397,compressor,191,1050,1800000.0,191,1954.275722,21780000.0,287.14,1246.846675,38.813101,1.299196,796.350164,0,12.1,0.94,2.084862e+08
1742398,compressor,191,1050,1900000.0,191,1954.275722,22990000.0,287.14,1246.846675,40.969384,1.299196,796.350164,0,12.1,0.94,2.084862e+08
1742399,compressor,191,1050,2000000.0,191,1954.275722,24200000.0,287.14,1246.846675,43.125668,1.299196,796.350164,0,12.1,0.94,2.084862e+08

## Compressor

In [35]:
features = [f"inlet_{gtep.mf}", f"inlet_{gtep.TT}", f"inlet_{gtep.PP}", gtep.pipi, gtep.effeff, gtep.power]
targets = (gtep.pipi, gtep.effeff, gtep.power, f"outlet_{gtep.TT}", f"outlet_{gtep.PP}")

In [38]:
test_size = 0.33

for target in (gtep.pipi, gtep.effeff, gtep.power):
    models = []
    for target_ in (target, f"outlet_{gtep.TT}", f"outlet_{gtep.PP}"):
        x, y = df[features], df[target_]
        x = x.drop([target], axis=1)
        print(target_, list(x.columns))

        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=test_size, shuffle=True)

        x_train = DictVectorizer(sparse=False).fit_transform(x_train.to_dict("records"))
        x_test = DictVectorizer(sparse=False).fit_transform(x_test.to_dict("records"))
        y_train = y_train.to_numpy()
        y_test = y_test.to_numpy()

        for Model in MODELS:
            model_name = Model.__name__
            print(f"\t{model_name}")
            model = Model()
            model.fit(x_train, y_train)
            for metric in METRICS:
                print(f"\t\t{Fore.YELLOW}{metric.__name__:<20}: {metric(y_test, model.predict(x_test)):.6f}{Fore.RESET}")

            with open(f"models/compressor_{target_}_{target}_{model_name}.pkl", "wb") as file:
                pickle.dump(model, file)

total_pressure_ratio ['inlet_mass_flow', 'inlet_total_temperature', 'inlet_total_pressure', 'total_efficiency', 'power']
	LinearRegression
		mean_absolute_error : 1.849775
		mean_squared_error  : 5.474865
	DecisionTreeRegressor
		mean_absolute_error : 0.000000
		mean_squared_error  : 0.000000
outlet_total_temperature ['inlet_mass_flow', 'inlet_total_temperature', 'inlet_total_pressure', 'total_efficiency', 'power']
	LinearRegression
		mean_absolute_error : 84.467126
		mean_squared_error  : 13317.852775
	DecisionTreeRegressor
		mean_absolute_error : 0.000000
		mean_squared_error  : 0.000000
outlet_total_pressure ['inlet_mass_flow', 'inlet_total_temperature', 'inlet_total_pressure', 'total_efficiency', 'power']
	LinearRegression
		mean_absolute_error : 2356819.714329
		mean_squared_error  : 10018946478290.431641
	DecisionTreeRegressor
		mean_absolute_error : 217940.040905
		mean_squared_error  : 274313709408.130890
total_efficiency ['inlet_mass_flow', 'inlet_total_temperature', 'inlet_total_pressure', 'total_pressure_ratio', 'power']
	LinearRegression
		mean_absolute_error : 0.027227
		mean_squared_error  : 0.000991
	DecisionTreeRegressor
		mean_absolute_error : 0.000000
		mean_squared_error  : 0.000000
outlet_total_temperature ['inlet_mass_flow', 'inlet_total_temperature', 'inlet_total_pressure', 'total_pressure_ratio', 'power']
	LinearRegression
		mean_absolute_error : 48.988254
		mean_squared_error  : 4206.769381
	DecisionTreeRegressor
		mean_absolute_error : 0.000000
		mean_squared_error  : 0.000000
outlet_total_pressure ['inlet_mass_flow', 'inlet_total_temperature', 'inlet_total_pressure', 'total_pressure_ratio', 'power']
	LinearRegression
		mean_absolute_error : 1498695.105555
		mean_squared_error  : 3957211355126.554688
	DecisionTreeRegressor
		mean_absolute_error : 0.000000
		mean_squared_error  : 0.000000
power ['inlet_mass_flow', 'inlet_total_temperature', 'inlet_total_pressure', 'total_pressure_ratio', 'total_efficiency']
	LinearRegression
		mean_absolute_error : 13367569.004371
		mean_squared_error  : 329786332553400.312500
	DecisionTreeRegressor
		mean_absolute_error : 0.000052
		mean_squared_error  : 0.000024
outlet_total_temperature ['inlet_mass_flow', 'inlet_total_temperature', 'inlet_total_pressure', 'total_pressure_ratio', 'total_efficiency']
	LinearRegression
		mean_absolute_error : 55.034285
		mean_squared_error  : 5264.902482
	DecisionTreeRegressor
		mean_absolute_error : 0.000000
		mean_squared_error  : 0.000000
outlet_total_pressure ['inlet_mass_flow', 'inlet_total_temperature', 'inlet_total_pressure', 'total_pressure_ratio', 'total_efficiency']
	LinearRegression
		mean_absolute_error : 1498762.064217
		mean_squared_error  : 3958588132429.688965
	DecisionTreeRegressor
		mean_absolute_error : 0.000000
		mean_squared_error  : 0.000000